const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),os=require('node:os'),path=require('node:path');
const {RainyunStorage}=require('../rainyun-storage.cjs');
const {publish}=require('../release-client.cjs');
function setup(t){const dir=fs.mkdtempSync(path.join(os.tmpdir(),'xc-s3-test-'));t.after(()=>fs.rmSync(dir,{recursive:true,force:true}));const name='XgoatCast-0.0.1-beta.2-win-x64-setup.exe',file=path.join(dir,name);fs.writeFileSync(file,'installer');let stored=null,puts=0;
 const client={async send(command){if(command.constructor.name==='HeadObjectCommand'){if(stored)return stored;const error=Error('missing');error.name='NotFound';throw error;}if(command.constructor.name==='PutObjectCommand'){puts++;assert.equal(command.input.IfNoneMatch,'*');assert.match(command.input.ContentDisposition,/attachment/);stored={ContentLength:9,Metadata:command.input.Metadata};return {};}}};
 const env={S3_ENDPOINT:'https://cn-sy1.rains3.com',S3_BUCKET:'xgoatcast-downloads'};
 const storage=new RainyunStorage(env,client,async()=>new Response(null,{headers:{'content-length':'9'}}));
 return {dir,file,name,storage,client,puts:()=>puts,setStored:value=>stored=value};}
test('installer upload is immutable, uses anonymous direct URL and reuses matching objects',async t=>{const f=setup(t);const args={file:f.file,name:f.name,version:'0.0.1-beta.2',checksum:'a'.repeat(64)};const result=await f.storage.publishFile(args);assert.equal(result.downloadUrl,'https://cn-sy1.rains3.com/xgoatcast-downloads/downloads/windows/official/0.0.1-beta.2/'+f.name);await f.storage.publishFile(args);assert.equal(f.puts(),1);f.setStored({ContentLength:9,Metadata:{sha256:'other'}});await assert.rejects(f.storage.publishFile(args),/不同内容/);assert.equal(f.puts(),1);});
test('private download leaves the latest release manifest unchanged',async t=>{const f=setup(t),releaseDir=path.join(f.dir,'releases');fs.mkdirSync(releaseDir);const latest=path.join(releaseDir,'latest.json'),before={version:'0.0.1-beta.1'};fs.writeFileSync(latest,JSON.stringify(before));f.storage.fetch=async()=>new Response(null,{status:403});await assert.rejects(publish({provider:'rainyun',file:f.file,version:'0.0.1-beta.2',notes:'修复',releaseDir,stateDir:path.join(f.dir,'state')},{},f.storage),/匿名公开/);assert.deepEqual(JSON.parse(fs.readFileSync(latest)),before);});
test('public installer updates manifest and history without exposing credentials',async t=>{const f=setup(t),releaseDir=path.join(f.dir,'public');const options={provider:'rainyun',file:f.file,version:'0.0.1-beta.2',notes:'更新',releaseDir,stateDir:path.join(f.dir,'state')};const result=await publish(options,{},f.storage);assert.equal(result.provider,'rainyun');assert.equal(result.downloadPassword,undefined);assert.equal((await publish(options,{},f.storage)).reused,true);assert.equal(f.puts(),1);const history=JSON.parse(fs.readFileSync(path.join(releaseDir,'history.json')));assert.deepEqual(Object.keys(history.releases[0]).sort(),['channel','notes','publishedAt','version']);});
